In [ ]:
pip install numpy matplotlib networkx

In [34]:
# Búa til slembifræ/seed út frá dagsetningunni
import numpy as np
seed = int(f"{13:02d}{12:02d}{2004}")
np.random.seed(seed)

# Búa til 4x4 slembifylki með 0 eða 1
fylki = np.random.randint(0, 2, size=(4, 4))

# Endirskrifa dagssetninguna á formið "dd-mm-yyyy"
formatted_date = f"{28:02d}-{5:02d}-{2001}"

# Prenta niðurstöður:
print(f"Fylkið fyrir dagsetninguna {formatted_date} og seed {seed}:")
print(fylki)
print()

Fylkið fyrir dagsetninguna 28-05-2001 og seed 13122004:
[[0 1 0 1]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 0 0]]



In [35]:
import numpy as np

def athuga_sjalfhverf(fylki):
    for i in range(len(fylki)):
        if fylki[i][i] != 1:
            return False
    return True

def athuga_samhverf(fylki):
    for i in range(len(fylki)):
        for j in range(len(fylki)):
            if fylki[i][j] != fylki[j][i]:
                return False
    return True

def athuga_andsamhverf(fylki):
    for i in range(len(fylki)):
        for j in range(len(fylki)):
            if i != j and fylki[i][j] == 1 and fylki[j][i] == 1:
                return False
    return True

def athuga_gegnvirk(fylki):
    for i in range(len(fylki)):
        for j in range(len(fylki)):
            for k in range(len(fylki)):
                if fylki[i][j] == 1 and fylki[j][k] == 1 and fylki[i][k] != 1:
                    return False
    return True

# Dæmi 4x4 fylki (slembifylki eins og búið var til áður)
# fylki = np.random.randint(0, 2, size=(4, 4))

# Prenta fylkið
print("Fylkið:")
print(fylki)

# Athuga eiginleikana
print(f"Fylkið er sjálfhverft: {athuga_sjalfhverf(fylki)}")
print(f"Fylkið er samhverft: {athuga_samhverf(fylki)}")
print(f"Fylkið er andsamhverft: {athuga_andsamhverf(fylki)}")
print(f"Fylkið er gegnvirkt: {athuga_gegnvirk(fylki)}")

#properties = check_properties(relation, set_elements)
#print(properties)

Fylkið:
[[0 1 0 1]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 0 0]]
Fylkið er sjálfhverft: False
Fylkið er samhverft: False
Fylkið er andsamhverft: True
Fylkið er gegnvirkt: True


In [ ]:
import networkx as nx
import matplotlib.pyplot as plt

def draw_relation_graph(relation, set_elements):
    G = nx.DiGraph()

    # Bæta við hnútum
    for node in set_elements:
        G.add_node(node)

    # Bæta við örvum fyrir venslin
    for (a, b) in relation:
        G.add_edge(a, b)

    # Teikna netið
    pos = nx.spring_layout(G)  # layout fyrir netið
    nx.draw(G, pos, with_labels=True, node_color='lightblue', node_size=2000, font_size=16, font_weight='bold', arrows=True, arrowstyle='-|>', arrowsize=20)
    plt.show()

# Dæmi um notkun:
relation = {(1, 1), (2, 2), (1, 2), (2, 1)}
set_elements = {1, 2}

draw_relation_graph(relation, set_elements)